classifier:
  name: "Классификация фрагментов ГОСТ"
  instruction: |
    Определи тип фрагмента ГОСТ-документа.
    Возможные варианты:
    - Требование — содержит обязательные условия, слова «должен», «обязан», «не допускается».
    - Рекомендация — допускает вариативность: «следует», «можно», «желательно».
    - Описание — даёт определения, пояснения, справочные сведения.
    Ответь одним словом: Требование / Рекомендация / Описание.

retrieval:
  name: "Инструкция для bi-encoder"
  index_prefix: "passage: "
  query_prefix: "query: "
  notes: |
    - Префиксы обязательны для E5: они активируют нужное пространство значений.
    - Лучше добавлять заголовок ГОСТа в начало чанка при индексации.

reranker:
  name: "Cross-Encoder для rerank"
  instruction: |
    Оцени, насколько данный фрагмент отвечает на вопрос. Верни число от 0 до 1.
  format:
    pair: ["{query}", "{chunk_text}"]
  notes: |
    - Работает через CrossEncoder.predict(pairs)

llm_answer:
  name: "Ответ от LLM"
  instruction: |
    Используй только предоставленные фрагменты ГОСТ как источник.
    Если ответа нет — так и скажи. Не выдумывай.
    Ответ должен быть точным, кратким и ссылаться на документ.
  format:
    input: |
      Вопрос: {query}
      Контекст:
      {top_k_chunks}
    output_example: |
      Согласно ГОСТ Р 51583-2014, средства должны обеспечивать контроль доступа пользователей.

llm_summary:
  name: "Суммаризация фрагментов"
  instruction: |
    Сформулируй краткое резюме смысловых требований из фрагментов ГОСТ.
    Не добавляй ничего от себя.
  format:
    input: |
      Фрагменты:
      {top_k_chunks}
    output_example: |
      Основные требования касаются защиты каналов связи и разграничения доступа.

llm_tz:
  name: "Формирование структуры ТЗ"
  instruction: |
    Составь структуру ТЗ по ГОСТу. Выдели разделы, кратко опиши их, оформи как JSON.
    Если тема не связана с ГОСТами — сообщи об этом.
  format:
    input: |
      Тема: {topic}
    output_example: |
      [
        {"Раздел": "Общие положения", "Описание": "Цели, область применения, нормативные ссылки"},
        {"Раздел": "Функциональные требования", "Описание": "Что должно делать ПО"}
      ]
