version: "3.9"

services:
  # === 1. EMBEDDER ===
  embedder:
    build: ./embedder
    container_name: gost1k_embedder
    ports:
      - "7000:7000"
    environment:
      - MODEL=intfloat/multilingual-e5-small
      - DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # === 2. RERANKER ===
  reranker:
    build: ./reranker
    container_name: gost1k_reranker
    ports:
      - "7001:7001"
    environment:
      - MODEL=BAAI/bge-reranker-base
      - DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  # === 3. INDEX (CHROMA) ===
  chroma:
    image: chromadb/chroma:latest
    container_name: gost1k_chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/chroma/chroma_db
    environment:
      - CHROMA_TELEMETRY_ENABLED=false

  # === 4. LLM (OLLAMA) ===
  llm:
    image: ollama/ollama:latest
    container_name: gost1k_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h

  # === 5. API (FastAPI Gateway) ===
  api:
    build: ./api
    container_name: gost1k_api
    ports:
      - "8080:8080"
    environment:
      - CHROMA_URL=http://chroma:8000
      - EMBEDDER_URL=http://embedder:7000
      - RERANKER_URL=http://reranker:7001
      - OLLAMA_URL=http://localhost:11434
    depends_on:
      - chroma
      - embedder
      - reranker
      - llm

volumes:
  ollama_models:
