embedding_model: "intfloat/multilingual-e5-small"
reranker_model: "BAAI/bge-reranker-base"
llm_model: "Qwen2:7B-Instruct"

docs_dir: "docs"
persist_dir: "chroma_db"
collection_name: "gost1k"

chunk_size: 720
chunk_overlap: 120
top_k: 20
top_n: 5

normalize_embeddings: true
use_gpu: true

ollama_url: "http://localhost:11434/api/generate"
batch_size: 64

log_level: "INFO"
